name: CD - Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    runs-on: ubuntu-latest
    needs: ci
    environment: deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
        
      - name: Install dependencies
        run: npm install --production
        
      - name: Build package
        run: npm run build
        
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}